---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
bibliography: references.bib
---

# Statistical plan {-}
\adjustmtc
\markboth{Statistical plan}{}
<!-- For PDF output, include these two LaTeX commands after unnumbered chapter headings, otherwise the mini table of contents and the running header will show the previous chapter -->

* Definition of a latent Gaussian model [@rue2009approximate]
  * Common examples
* Examples of models used in HIV inference which are close to being latent Gaussian models, but aren't, and hence can't be fit using INLA
  * Disaggregation models
  * Evidence synthesis models like Naomi [@eaton2021naomi; @eaton2019joint]
  * Compartmental models
  * ART attendance models
  * Multinomial models like for district-level risk factors
* Definition of extended latent Gaussian models [@stringer2021fast]
  * Many-to-one is not an issue for `R-INLA`, the latent field is implemented as a concatenation of many vectors already. For example, for $\eta_i = \beta_0 + \phi_i$ with $i = 1, \ldots, n$ the latent field is $(\eta_1, \ldots, \eta_n, \beta_0, \phi_1, \ldots, \phi_n)^\top$ of dimension $2n + 1$
  * For additive models, the only non-linearity is in the link function
* Approximate Bayesian inference methods
  * Markov chain Monte Carlo
  * Variational Bayes
  * Laplace approximation and integrated nested Laplace approximation
  * Empirical Bayes
* Particular properties of spatio-temporal models (and LGMs) which make INLA, if feasible, often the best option
* The increasing popularity of empirical Bayes approaches, like Template Model Builder [@osgoodzimmerman2021statistical]
* Adaptive Gauss Hermite quadrature (AGHQ), like the central composite design (CCD) and grid strategies, is one way to choose the hyper-parameter integration points in the integrated nested Laplace approximation (INLA)
* Finn Lindgren is working on a method for non-linear predictors, called the [iterative INLA method](https://github.com/inlabru-org/inlabru/blob/55896f10d563c14e34cab577b29b733aac051f86/vignettes/method.Rmd)
* Thesis work of [Follestad](https://cds.cern.ch/record/639625/files/sis-2003-305.pdf) that stayed as a preprint

<!-- How does the ecological fallacy relate to aggregated output models -->
