---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: references.bib
---

# Background {-}
\adjustmtc
\markboth{Background}{}
<!-- For PDF output, include these two LaTeX commands after unnumbered chapter headings, otherwise the mini table of contents and the running header will show the previous chapter -->

* Brief summary of the HIV/AIDS epidemic, up to the situation now, focusing on SSA
* The historic role of surveillance techniques and statistical models in responding to the epidemic
* The aims for HIV response going forward, and what surveillance capabilities are needed to meet them
* Data difficulties
  * Sparsity in space and time
  * Survey bias
  * Conflicting information sources
  * Hard to reach populations
  * Demography, knowing the correct denominator
* Phasing out of nationally-representative household surveys for HIV
  * Importance of relying on multiple sources of information: evidence synthesis, Naomi, multivariate models
  * Bayesian survey design
* Why isn't case-based surveillance included yet?
  * There aren't individual linked databases and patient records have to be consolidated
  * Passive case-based surveillance
  * Post-hoc matching and create a case-based surveillance record
* Key HIV indicators
  * HIV prevalence
  * HIV incidence
  * ART coverage
  * Coverage of other interventions such as PrEP, PEP
* Drivers of transmission
* Possible interventions
  * ART
  * Condoms
  * PrEP and PEP
  * Education
  * Economic empowerment
  * VMMC
* Geographic targeting versus demographic targeting
  * Hotspots
  * Key populations
  * Screening and individual level risk characteristics
* Adolecent girls and young women identified as a key demographic
  * Stratification by sexual risk
* Interventions more likely to be demographic specific rather than geographic specific
  * If majority of difference in effectiveness depends on intervention type then demographic targeting may be more priority
* Small-area estimation in health, epidemiology and environment
  * The Small-Area Health Statistics Unit at Imperial was set-up to monitor health around point sources of environmental pollution in response to the Sellafield enquiry into the increased incidence of childhood leukemia leukaemia near a nuclear reprocessing plant [@elliott1992small]. This research has a focus on ratios of observed events to expected events, and testing hypothesis about hot-spots

## 19th October meeting

* Calculate empirical averages of categories (as for what to expect for category random effects)
* Fit a single survey model for all categories
* There are five countires where there exists good FSW data, fit the model there
* Important to talk about what is going on with non-regular partners in South Africa
* We will have more FSW data in future
* Look to submit to e.g. Lancet Child & Adolescent Health or PLoS Global Health
* Future work extending Laga et al. to use country elicited random error inflation, CFSW data, generalisation from countries with good survey data, in TMB or `aghq`
* Results shouldn't change when the constraints change
* Review posterior predictive estimates used for coverage
* Look at including PHIA or MICS
* Write a more extended version of the DHS survey questions
* Take posterior of 3rd category and use some post-hoc procedure to get the 4th category 

## Clemens UNAIDS meeting

* High prevalence and incidence is the main criteria for Global Fund priority
* How can we develop an operational aid for using the spreadsheet as a programmatic planning tool? How should the information be used in practise?
* How to find people within the district who fall under each category?
* There is some non-zero contribution of not sexually active individuals to HIV incidence (e.g. drug injectors). Particularly if extend to men then might have to take it into account. In some countries the population of drug injectors is small but not neglible
* How to capture the potential effects of interventions?
* What is the development plan for including ABYM? Extension to adults aged 15-49?
* Where is new technology required?
* If a country has very old data should there be a warning about this?
* Dependence of FSW on clustering and migration



<!-- The population strategy strategy of Geoffrey Rose https://en.wikipedia.org/wiki/Geoffrey_Rose_(epidemiologist) -->