---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
bibliography: references.bib
---

# Conclusions {#conclusions}
\adjustmtc
\markboth{Conclusions}{}
<!-- For PDF output, include these two LaTeX commands after unnumbered chapter headings, otherwise the mini table of contents and the running header will show the previous chapter -->

<!-- JWE: Minor corrections often involve (1) fixing typos, (2) clarifying things, (3) elaborating on the contributions to science and implications of the PhD in the conclusions chapter [by far the most common point of examiner feedback] -->

This chapter concludes the thesis by discussing the most important contributions, limitations, promising avenues for future work, and broader reflections about the work.

## Contributions

Chapter \@ref(beyond-borders) used tools for model assessment such as proper scoring rules and posterior predictive checks to comprehensively compare models for spatial structure.
Useful data for practitioners.
Useful to base methodological developments on.

Chapter \@ref(multi-agyw) estimated HIV risk group proportions for AGYW to enable implementation of the Global AIDS strategy.
Risk group proportion estimates were used to disaggregate HIV prevalence and incidence estimates by behaviour, and assess the benefits of a variety of risk stratification strategies.
This work forms the basis for a tool used to prioritise delivery of HIV prevention services by countries in SSA.
The tool is to be updated by UNAIDS as a part of the annual HIV estimates process.
Alongside these applied contributions, Chapter \@ref(multi-agyw) exemplified specification of complex multinomial spatio-temporal models in `R-INLA` using the Poisson-multinomial transformation, including using two- and three-way Kronecker product interactions.

Chapter \@ref(naomi-aghq) developed deterministic Bayesian inference methods, motivated by a challenging and practically important problem in evidence synthesis for small-area estimation of HIV indicators.
Its most important contributions are two-fold.
First, an implementation of INLA which is compatible with models specified using a `TMB` C++ template.
Notably, this contribution enables practitioners to fit essentially any model using INLA for the first time.
Second, a quadrature rule which naturally extends the applicability of INLA methods to moderate hyperparameter dimension.

## Limitations

The work done in this thesis, particularly Chapters \@ref(beyond-borders) and \@ref(naomi-aghq), focused on producing empirical evidence, using experimentation.
In part, this approach reflects the complexity of the models and methods used in this thesis.
Understanding complex systems from a theoretical perspective can be challenging.
That being said, much of the work done in this thesis would benefit from closer integration with statistical theory.
Though end-to-end theoretical understanding is unlikely, value could come from better understanding of limiting cases, simplified examples, and steps in complete procedures.

In working most tangibly with real world data, Chapter \@ref(multi-agyw) inherits a wide range of limitations.
To highlight a few:
the external validity of risk ratios derived from cohort studies across all settings.

## Future work

Promising avenues for future work that I would prioritise include:

1. Although AGYW are disproportionately at risk of HIV infection, 56% of new infections in SSA occur in other demographic groups.
As such, it would be valuable to extend the risk group model developed in Chapter \@ref(multi-agyw), and the derived prioritisation tool, to include all adults 15-49.
This might involve modelling of age-stratified sexual partnerships [@wolock2021evaluating].
Such a model would likely fall out of the scope of `R-INLA`, but would be possible to write with `TMB` and therefore amenable to the inference methods advanced in Chapter \@ref(naomi-aghq).

2. Practical use of the INLA implementation developed in Chapter \@ref(naomi-aghq) would benefit significantly from improvements to its speed and usability.
The most important speed enhancement would likely come from using the simplified approximation to the Laplace marginals developed by @wood2020simplified.
Usability would be improved by integration of the method into statistical software, first and foremost via the `aghq` package.
The primary difficulty, as it appears now, which would have to be overcome is that the `random` argument of `TMB::MakeADFun` does not allow indexing.

3. The universal INLA implementation developed in Chapter \@ref(naomi-aghq) is enabling of methodological research.
For example, INLA-like methods can now be tested for a broader class of models, such as the Loa loa and Naomi ELGMs (Sections \@ref(loaloa) and \@ref(malawi)).
For this purpose, it is particularly important that the `TMB` C++ template for the log-posterior supports inference using multiple methods, including gold-standard NUTS via `tmbstan`.
Within this broader class of models, I wonder about the best way to achieve accurate results given a certain computational budget.
How should computational effort be traded-off between additional hyperparameter grid points and more accurate latent field approximations?
For example, for the Loa loa ELGM, the accuracy benefit of using Laplace marginals was more than increasing the number of AGHQ nodes per dimension from $k = 3$ to $k = 7$ (Figure \@ref(fig:conditional-simulation-diff-k-fixed)).
Additional theoretical work could be conducted to complement the empirical work described above.
This work could be benefited by the exhaustive specification of the INLA-like algorithms used in this thesis.

## Broader reflections

Conducting the work in this thesis involved testing the boundaries of available statistical software.
For example, I found it challenging, if not impossible, to implement a common model using different inferential software.
As the frequently asked questions section of the `R-INLA` website [@rinla2023faq] notes: "the devil is in the details".
Similarly, I encountered difficulties implementing a desired collection of different models in a common inferential software.
If not addressed, these difficulties would result in conflation of statistical models and inference methodologies, limiting the validity of any findings.
Ultimately, I resolved these issues by implementing all models in Chapters \@ref(beyond-borders) and \@ref(naomi-aghq) using `TMB` model templates.
(Additionally, I would recommend implementing the model used in Chapter \@ref(multi-agyw) in `TMB` for future development.)
Alongside being sufficiently flexible to meet my model specification requirements, `TMB` is compatible with a range of inference methodologies (including those contributed to in this thesis).
As such, `TMB` remains [@osgood2023statistical] an under-rated statistical tool.
In demonstrating some of its capabilities, I hope that this thesis might contribute to its wider adoption.

There are both direct and indirect paths to impact for the work in this thesis.
Directly, the methodological contributions of Chapters \@ref(beyond-borders) and \@ref(naomi-aghq) may eventually lead to marginally more accurate indicator estimates, contributing to a broadly more effective response.
However, these improvements in accuracy seem of quite minor consequence within the broader context of the HIV response and the factors limiting its effectiveness.
The applied contributions of Chapter \@ref(multi-agyw) have a more promising case for direct impact.Is

To the best of my abilities, this thesis, and the work described within it, was written in keeping with the principles of open science.
I hope that having done so facilitates my work to be scrutinised, and more optimistically, built upon.
This would not have been possible without tools from the R ecosystem such as `rmarkdown` and `rticles` for reporting, `devtools` for R package development, as well as those written by software engineers within the MRC Centre for Global Infectious Disease Analysis such as `orderly` and `didehpc`.

<!-- Aims for HIV response going forward, and the surveillance capabilities needed to meet them. -->
<!-- Greater reliance on routine health system data. -->
<!-- It is not recommended to include HIV testing in nationally representative household surveys in low (<2%) HIV prevalence settings [@world2005guidelines]. -->
<!-- Patient-level HIV data systems [@world2017consolidated] and case-based surveillance (CBS). -->
<!-- Integration of HIV services with other health programs and strengthening of health systems. -->
