---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: references.bib
---

# Future plans {-}
\adjustmtc
\markboth{Future plans}{}
<!-- For PDF output, include these two LaTeX commands after unnumbered chapter headings, otherwise the mini table of contents and the running header will show the previous chapter -->

* Potential academic groups of interest
  * DIDE
  * BDI
  * Samir Bhatt's group at Copenhagen
  * Turing-RSS Lab (Marta Blangiardo, Peter Diggle, Chris Holmes, Sylvia Richardson)
* Potential non-academic groups of interest
  * National Institute for Biological Standards and Control
* Potential topics of interest
  * Wastewater surveillance
    * Connected to ecological regression (somehow)
* Some of Seth's comments about surveillance
  * [Swapnil's eClinicalMedicine paper](https://www.thelancet.com/journals/eclinm/article/PIIS2589-5370(21)00344-8/fulltext)
    * Symptom based testing S+ and random sampling S+, one is available a week or two earlier, different lags
  * Varying levels of signal from varying signals
  * What's representative, what's biased in different ways
  * Big data paradox (bias decomposition identity)
  * How are countries and labs incentivised to contribute to a global surveillance system? How to avoid punative measures for countries which report early e.g. ZAF for Omicron 
