# Welcome {-}

This is the e-book version of my PhD thesis, submitted to Imperial College London in accordance with the requirements of the degree of Doctor of Philosophy in Modern Statistics and Statistical Machine Learning.
If you would prefer, you can view the [PDF version](https://athowes.github.io/thesis/main.pdf).
The associated GitHub repository for this thesis is [`athowes/thesis`](https://github.com/athowes/thesis).
A concise introduction to the work is available via my thesis defense [slides](https://athowes.github.io/thesis/slides.pdf), or (slightly less concise) longer [slides](https://athowes.github.io/thesis/slides-long.pdf) for a lab group meeting.
The [corrections](https://athowes.github.io/thesis/correct.pdf) for this thesis are also available online.
If you notice any typos or other issues with the work, feel free to open an [issue](https://github.com/athowes/thesis/issues) on GitHub, or submit a pull request.

## Acknowledgments {-}

```{r acknowledgments, child=here::here('front-and-back-matter/_acknowledgements.Rmd')}
```

## Abbreviations {-}

| Abbreviation | Definition                                       |
|:-------------|:-------------------------------------------------|
| AIDS         | Acquired ImmunoDeficiency Syndrome               |
| AIS          | AIDS Indicator Survey                            |
| ANC          | Antenatal Clinic                                 |
| AGHQ         | Adaptive Gauss-Hermite Quadrature                |
| ART          | Antiretroviral Therapy                           |
| BIC          | Bayesian Information Criterion                   |
| BF           | Bayes Factor                                     |
| CAR          | Conditionally Auto-regressive                    |
| CCD          | Central Composite Design                         |
| CDC          | Centers for Disease Control and Prevention       |
| CPO          | Conditional Predictive Ordinate                  |
| CRPS         | Continuous Ranked Probability Score              |
| DALY         | Disability Adjusted Life Year                    |
| DDC          | Data Defect Correlation                          |
| DHS          | Demographic and Health Surveys                   |
| DIC          | Deviance Information Criterion                   |
| EB           | Empirical Bayes                                  |
| ECDF         | Empirical Cumulative Difference Function         |
| ELGM         | Extended Latent Gaussian Model                   |
| ESS          | Effective Sample Size                            |
| FSW          | Female Sex Worker(s)                             |
| GA           | Gaussian Process                                 |
| GLM          | Generalised Linear Model                         |
| GLMM         | Generalised Linear Mixed effects Model           |
| GMRF         | Gaussian Markov Random Field                     |
| Global Fund  | Global Fund to Fight AIDS, Tuberculosis, and Malaria |
| HMC          | Hamiltonian Monte Carlo                          |
| HIV          | Human Immunodeficiency Virus                     |
| ICAR         | Intrinsic Conditionally Auto-regressive           |
| IID          | Independent and Identically Distributed          |
| INLA         | Integrated Nested Laplace Approximation          |
| LM           | Linear Model                                     |
| LGM          | Latent Gaussian Model                            |
| LS           | Log Score                                        |
| MCMC         | Markov Chain Monte Carlo                         |
| MSM          | Men who have Sex with Men                        |
| NUTS         | No-U-Turn Sampler                                |
| PEP          | Post-Exposure Prophylaxis                        |
| PEPFAR       | President’s Emergency Plan for AIDS Relief       |
| PHIA         | Population-based HIV Impact Assessment           |
| PIT          | Probability Integral Transform                   |
| PLHIV        | People Living with HIV                           |
| PPL          | Probabilistic Programming Language               |
| PrEP         | Pre-Exposure Prophylaxis                         |
| PMTCT        | Prevention of Mother-to-Child Transmission       |
| PWID         | People Who Inject Drugs                          |
| SAE          | Small-Area Estimation                            |
| SR           | Scoring Rule                                     |
| SPSR         | Strictly Proper Scoring Rule                     |
| SSA          | Sub-Saharan Africa                               |
| STI          | Sexually Transmitted Infection                   |
| TGP          | Transgender People                               |
| TaSP         | Treatment as Prevention                          |
| UNAIDS       | The Joint United Nations Programme on HIV/AIDS   |
| VI           | Variational Inference                            |
| VMMC         | Voluntary Medical Male Circumcision              |
| WAIC         | Watanabe-Akaike Information Criterion            |

## Notations {-}

| Notation     | Definition                                             |
|:-------------|:-------------------------------------------------------|
| $\propto$    | Proportional to.                                       |
| $\mathbb{R}$ | The set of real numbers.                               |
| $\mathbb{Z}$ | The set of integers.                                   |
| $\mathbb{Z}^+$ | The set of positive integers.                        |
| $\rho$       | HIV prevalence.                                        |
| $\lambda$    | HIV incidence.                                         |
| $\alpha$     | ART coverage.                                          |
| $\mathcal{S}$ | Spatial study region $\mathcal{S} \subseteq \mathbb{R}^2$. |
| $s \in \mathcal{S}$ | Point location.                                 |
| $\mathcal{T}$ | Temporal study period $\mathcal{T} \subseteq \mathbb{R}$. |
| $t \in \mathcal{T}$ | Time.                                           |
| $\mathbf{y}$ | Data, a $n$-vector $(y_1, \ldots, y_n)$.               |
| $\boldsymbol{\phi}$ | Parameters, a $d$-vector $(\phi_1, \ldots, \phi_d)$. |
| $\mathbf{x}$ | Latent field, a $N$-vector $(x_1, \ldots, x_N)$.       |
| $\boldsymbol{\theta}$ | Hyperparameters, a $m$-vector $(\theta_1, \ldots, \theta_m)$. |
| $x \sim p(x)$ | $x$ has the probability distribution $p(x)$.          |
| $A_i$        | Areal unit.                                            |
| $A_i \sim A_j$ | Adjacency between areal units.                       |
| $\mathbf{u}$ | Random effects, often spatial.                         |
| $\mathbf{H}$ | Hessian matrix.                                        |
| $\mathbf{R}$ | Structure matrix.                                      |
| $\mathbf{Q}$ | Precision matrix.                                      |
| $\boldsymbol{\mathbf{\Sigma}}$ | Covariance matrix.                   |
| $\mathbf{M}^{-}$ | The generalised inverse of a (potentially rank-deficient) matrix $\mathbf{M}$. |
| $\mathcal{N}$ | Gaussian distribution.                                |
| $k: \mathcal{X} \times \mathcal{X} \to \mathbb{R}$ | Kernel function on the space $\mathcal{X}$. |
| $A_i \sim A_j$ | Adjacency between areal units.                       |
| $\mathcal{Q}$ | A set of quadrature nodes.                            |
| $\omega: \mathcal{Q} \to \mathbb{R}$ | A quadrature weighting function. |
| $\mathcal{Q}(m, k)$ | Gauss-Hermite quadrature points in $m$ dimensions with $k$ nodes per dimension, constructed according to a product rule. |
| $\varphi$    | A standard (multivariate) Gaussian density.            |
