---
title: Thesis revisions requested by Chris Paciorek
subtitle: |
  Typeset by Adam Howes (`ath19@ic.ac.uk`)
output:
  pdf_document:
    toc: true
    number_sections: true
    keep_tex: true
---

# General comments

## Chapter 4

Chapter 4 explores different types of spatial smoothing with areal data, motivated by potential shortcomings of the commonly-used Besag (basic adjacency) model. I'd like to see some more context relating the potential shortcomings to the public health setting (you have a bit of this in Section 4.1.3). For a public health analyst, when might they be most concerned about using the Besag model? What kinds of areal arrangements/neighborhood structures/types of data might be most prone to concern? E.g., one might be concerned about cases like Canadian provinces where their populations are so concentrated right near neighboring US states and most of the provincial area is sparsely populated. And as we discussed, I'd like for you to see if you can drill down into the localized results of the simulation to give some insight into where the smoothing is sub-optimal in the simulations. Relatedly would you expect the features highlighted by your vignettes to occur in reality in public health settings?

## Chapter 5

Chapter 5 presents an applied analysis that attempts to figure out how to prioritise strata of the population to reach the most people at danger of new infection. It combines a variety of sources of information, with a key piece being fully inferential modeling of risk group proportions based on survey data. I'd like to see the chapter initially clearly lay out the overall goal, the quantitative representation of that, the various pieces of the analysis and how they fit together, and the data available, as well as what components you can estimate uncertainty for. In particular the notion of "reaching" the population needs to be clearly spelled out initially. And as we discussed, please make clear how prevalence is needed.

Model 5.11 omits various interactions. Focusing on the category-area-age interaction, which seems like the omitted interaction most likely to have substantial variation in reality, some effort to come up with some "residual" type diagnostic to assess model mis-specification in this regard would be helpful (e.g., perhaps some sort of variogram type analysis of some sort of age-group specific "working residuals" to borrow a GLM framing). Or you mentioned fitting the model with the interaction for one country. If that is not too burdensome that would also be a reasonable approach here.

The distinct differences between the CPO and information criteria (IC) results (and the very structured pattern in the surprising IC results) suggest the possibility of a bug somewhere, as we discussed. Getting the observation-specific values from INLA might help to better understand this.

## Chapter 6

Chapter 6 extends standard INLA computation in two ways. For the second (using PCA to reduce quadrature points), it is clear how this is new. For the first, I'd like to see more clarity in how this differs from the Stringer et al. (2022) approach (i.e., that you go beyond the Gaussian mixture over the quadrature points, as we discussed in the defense) and the details of the software implementation (e.g., giving an overview in the chapter describing what someone would need to do to make use of your code/approach).

As we discussed in the defense, I'm concerned about any case where one draws from marginals, implicitly assuming no dependence, either at the hyperparameter level or the latent process level, and then does inference on a derived quantity that depends on more than one input. You should be clear anytime you do this that this is problematic (and try to avoid as much as possible).

Relatedly, assuming I'm understanding correctly, there is an important tradeoff between using Laplace marginals for improved accuracy for latent marginals and using the Gaussian mixture over the quadrature points, which allows one to make draws and do inference on any derived quantity in a way that takes account of posterior dependence between and amongst hyperparameters and latent process values. If that's the case, I think it's worth pointing this out and discussing when one can use the Laplace marginals in a public health context and when one might need to use the Gaussian mixture.

# Minor comments

(and pointing out typos), by page number in PDF. (Some of this is pretty terse - feel free to reach out to me if anything is unclear.)

* 4: "develop into a stage" -> "Infection with HIV can"
* 6: "to result a reduction"
* 11: "Both DHS and PHIA surveys collecting"
* 12: individual disclosure: error may come from them not knowing status
* 14: "UNAIDS process"
* 16 (and elsewhere): Please look up usage of "that" vs. "which" so you can join me in the grammar police. "Models which do not produce" -> "Models that do not produce"
* Fig 3.1: I suggest that you also show the likelihood.
* 17: Beyond just p(y) even if you know the full form of p(phi|y) what do you do with it in non-trivial dimensions? You have to be able to either draw from it or estimate expectations of interest. So the issue is rather broader than just the unknown normalizing constant.
* 19. You haven't defined 'convergence' when you dive into diagnostics.
* 21. I'd frame this as deterministic approximations need to focus on approximating expectations of interest. I think of Laplace as approximating an integral over part of parameter space (often 'random effects') to be able to work with a smaller-dimensional space, such as for maximization.
* 23. "data is" -> "data are" (also p 66 and perhaps elsewhere)
* 30. You distinguish ELGM from LGM with having defined eta for LGM or been explicit about 1:1 relationship of x and y.
* Sec 3.4: worth commenting on additivity of these measures that treat each obs as a unit of information given you are in a spatial setting.
* 35. (3.30) should be for $\pi_{2hj}$.
* 37. "difficultly"
* 37. "arrived at using by"
* 41. Might be worth including the variance piece raised to the power `n-c`.
* 41. "recommended against": passive, and by who?
* 42. Why is unit variance correct?
* 47. tau_v an d tau_w are not orthogonal - what does this mean?
* 48. Is convolution the right term here?
* 55: what is meant by "model is implemented in arealutils"?
* 56: need citation for v being hard to estimate
* 56: have Li vary with size?
* 56: effect -> affect
* 57: "and the calibration"
* 57: What parameter is shown in Figs 4.7-4.9 - it's not clear you're assessing the latent process values. And in that case you should be clear the CRPS is averaged over locations.
* 59: Explain that mean CRPS is mean over the simulations.
* 63: Table 4.4 has no standard errors.
* 64: "resulted wide"
* 64: surprisingly
* 67: "This chapter used of area-level models to for point-level data throughout". I can't parse this. You can only use point level model if have point level data.
* 67: "measures are disaggregated by area" - not sure of the point here.
* 71: FSW is not defined in Table 1 caption.
* 71: In Table 1 why does High risk group IRR not vary with local incidence?
* 71: Purpose of Table 1 is not clear. Nor how IRR is to be used.
* Tables sometimes appear earlier than they should (e.g., 5.1 and 5.2).
* 77: Table 5.2: phi_{ik} should be u_{ik}.
* 80: Mention country-specific vs single models earlier.
* 82: I would say clearly that model structure for q_ia is discussed next.
* 85: First paragraph of 5.3.3 is a bit hard to follow.
* 86: The bio-marker survey data and disaggregation model is unclear. How are risk groups known for individuals in the survey?
* 88: Section 5.4.3 is hard to understand. I don't understand how it relates to 5.4.2. "Reach" is not clearly defined nor is it clearly discussed how it is quantified based on the various modeling * pieces.
* 91: Not clear what the quantities are in the statement about "in most districts adolescent girls aged 15-19 were not sexually active". Is this an across-district or within-district quantity?
* 95: does the approach presented allow identification of actual people or just targeting efforts to reach more such people collectively
* 96: "Accounting for the 0% of new infections"?
* 106: Not sure what you mean by "log p(y|x,theta) is small". This is the likelihood...
* 116: "in which, which"
* 122: "Method" in Table 6.1 a bit terse.
* 122: Is "Gaussian, EB" the same as frequentist Laplace approx (up to hyperparameter prior)? If so, probably worth saying.
* 130: Somewhat unclear how the quadrature is implemented, wrapped around the TMB-based Laplace approximation. Is your code in R? (Sorry, this may be because I didn't have time to look through
* appendices.)
* 131: Using same number of iterations with stan (full posterior, including latent values) vs tmbstan (hyperparameters, much lower-dimensional space) seems odd.
* 132: Fig 6.7 is just grid/AGHQ, not EB? If so, why present EB method?
* 132: Why surprising tmbstan faster than rstan - what are the different computations involved - having to compute Laplace vs doing HMC over higher dimensional space. I expect it would vary with hyperparameter and latent dimensions.
* 136: "kridge" -> "krige"
* 137: "this" in "this difference" is unclear.
* 143: "survey weighting increases variance" - what about effect of increasing precision in small strata? Are you talking about influence of complex survey design or somehow about weighting scheme?
* 149: INLA uses CCD for d>2, right? Would this not work for this setting?
* 151: (6.97) has 'd' instead of 'm'
* 154: "closet"
* 154: Did you use MAP for theta when looking at Hessian eigenvalues?
* 156: "Figure ??"
* 156: "far fewer than full 24" - is this a problem?
* 156: "point estimates" "distributional quantities" - need "and"
* 157: Need caption to describe the green
* 165: What went wrong with tmbstan?