rmarkdown::render(input = "corrections/corrections.Rmd", output_dir = "docs")
pagedown::chrome_print(input = "corrections/cover.Rmd", output = "docs/cover.pdf", extra_args = c("--disable-http-cache"))
pdftools::pdf_combine(c("docs/cover.pdf", "docs/corrections.pdf"), output = "docs/correct.pdf")
file.remove("docs/corrections.pdf")
file.remove("docs/corrections.tex")
file.remove("corrections/cover.html")
unlink("corrections/cover_files/", recursive = TRUE)
unlink("corrections/corrections_cache/", recursive = TRUE)
